#!/usr/bin/env python

import sys

# from heron_interact.my_module import MyPlugin
# from heron_interact.image_path_selector import ImagePathSelector
from heron_interact.heron_gui import HeronGUI
from rqt_gui.main import Main

plugin = 'mymodule'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
