ugv:
  # robot_running: True
  robot_running: False
  cmd_manager_action: "/robot/command_manager/action"
  cmd_sequencer_action: "/robot/command_sequencer/action"
  cmd_manager_srv: "/robot/command_manager/command"
  cmd_sequencer_srv: "/robot/command_sequencer/command"
  move_through_path: "/robot/heron_manipulation/move_through_path"
  move_to_action: "/robot/arm/move_to"
  move_to_pose_action: "/robot/arm/move_to_pose"
  pickup_from_action: "/robot/arm/pickup_from"
  place_on_action: "/robot/arm/place_on"
  dock_action: "/robot/base/dock"
  odom_topic: "/robot/odom"
  find_offset_srv: "/robot/find_offset"
  get_deposit_srv: "/robot/get_deposit_sequence"
  body_cam_ns: "/robot/body_camera/body_camera"
  body_cam_frame: "robot_lifting_unit_camera_rgb_camera_optical_frame"
  arm_cam_ns: "/robot/arm_camera"
  arm_cam_frame: "robot/arm_camera_rgb_camera_optical_frame"
  base_frame: "robot_base_footprint"
  map_frame: "robot_map"
  odom_frame: "robot_odom"

kafka: False

iccs:
  find_pothole_srv: "/find_potholes"
  find_cracks_srv: "/find_cracks"

pothole:
  offset: 2.0
  inspection_names: 
    - "inspection_mid_old"
    - "inspection_left"
    - "inspection_right"
  roller_sequence:
    - "POT_FB_1" # first tank
    - "POT_FB_2" # second tank
    - "POT_FB_3" # third tank
    - "POT_ROLL_OVER" 

cone_place:
  offset: 0.7
  is_left_side: True
  gps_points:
    - [37.7745, -122.4195]  # P1
    - [37.7745, -122.4185]  # P2
    - [37.7740, -122.4197]  # P3
    - [37.7740, -122.4190]  # P4
    - [37.7740, -122.4183]  # P5

cracks: 
  offset: 0.7
  is_right_side: True
  # is_right_side: False
  max_length: 0.6

#TODO position in dummy file & hardcoded pothole size&loc
test:
  arm: True
  comp: False
  img: False
